# Generated by Django 4.2.7 on 2023-11-16 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('biography', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.PositiveIntegerField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_auther', to='book.auther')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=5000)),
                ('rating', models.PositiveIntegerField(help_text='enter the review from 1 to 5 only')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_review', to='book.book')),
            ],
        ),
    ]
