# Generated by Django 4.2.7 on 2023-11-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auther_book', to='book.book'),
            preserve_default=False,
        ),
    ]
