# Generated by Django 4.2.7 on 2023-11-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auther_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='book',
        ),
    ]
