# Generated by Django 4.2.7 on 2023-11-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_auther_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='book.review'),
        ),
    ]
