# Generated by Django 4.2.7 on 2023-11-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
    ]
