# Generated by Django 4.2.7 on 2023-11-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auther_book_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
    ]
