# Generated by Django 4.2.7 on 2023-11-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_auther_book_remove_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='book',
            field=models.ForeignKey(default='book1', on_delete=django.db.models.deletion.CASCADE, related_name='auther_book', to='book.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='book.review'),
            preserve_default=False,
        ),
    ]
